name: Release
on:
  release:
    types:
      - published

jobs:
  build:
    strategy:
      matrix:
        platform: [macOS-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Parse Event
        id: event
        run: |
          echo "::set-output name=tag::$(jq -r '.release.tag_name' "${GITHUB_EVENT_PATH}" | sed s/^v//)"
      - name: pack
        id: pack
        run: |
          # pack
          cd .workflow
          zip -r ../"ForkOpen-${{ steps.event.outputs.tag }}.alfredworkflow" .
          cd ..

          echo "::set-output name=artifact::$(echo "ForkOpen-${{ steps.event.outputs.tag }}.alfredworkflow")"
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "${{ steps.build.outputs.artifact }}"
